# Goal is to call the workflows in the order to implement shift left

name: DevSecOps 

on: 
    push:

jobs:

    # Secrets Scan
    secret-scan:
        uses: ./.github/workflows/secrets-scanning.yml
        secrets: inherit
        
    # Code
    code:
        needs: secret-scan
        uses: ./.github/workflows/lint-test.yml
   
    #sonar-scan
    sonar-scan:
        needs: code
        uses: ./.github/workflows/sonar_scan.yml
        secrets: inherit

    # Dependency Scan
    dependency-scan:
        needs: sonar-scan
        uses: ./.github/workflows/dependency_scan.yml

    # Build and Scan
    build-and-scan:
        secrets: inherit
        needs: dependency-scan
        uses: ./.github/workflows/trivy_scans.yml
    
    # Image Push to DockerHub
    docker-push:
        secrets: inherit
        needs: build-and-scan
        uses: ./.github/workflows/docker_push.yml

    
    # Deploy
   #  deploy:
    #   secrets: inherit
     #  needs: [code,build-and-push]
     #  uses: ./.github/workflows/cd.yml